version: "3.8"

services:
    configserver:
        image: myconfigserver:latest
        mem_limit: 700mb
        ports:
            - "8084:8084"
        networks:
            - abc-networks
            
    eurekaserver:
        image: myeurekaserver:latest
        mem_limit: 700mb
        ports:
            - "8085:8085"
        networks:
            - abc-networks
        depends_on:
            - configserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/

        

    account:
        image: accountms:latest
        mem_limit: 700mb
        ports:
            - "8083:8083"
        networks:
            - abc-networks
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/
            
          
    cust:
        image: custms:latest
        mem_limit: 700mb
        ports:
            - "8082:8082"
        networks:
            - abc-networks
        depends_on: 
            - configserver
            - eurekaserver
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            SPRING_PROFILES_ACTIVE: default
            SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/

   
networks:
     abc-networks:


